{% set name = "wrk" %}
{% set version = "4.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/wg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e255f696bff6e329f5d19091da6b06164b8d59d62cb9e673625bdcd27fe7bdad

build:
  number: 0
  skip: true  # [win or osx]
  # osx:
  # Undefined symbols for architecture x86_64:
  # "_getentropy", referenced from:
  #     _lj_prng_seed_secure in libluajit.a(lj_prng.o)

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - unzip
  host:
    - openssl

test:
  commands:
    - wrk -c 1 -t 1 -d 1 https://example.com/

about:
  home: https://github.com/wg/wrk
  summary: Modern HTTP benchmarking tool
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - obj/LuaJIT-2.1/COPYRIGHT

extra:
  recipe-maintainers:
    - jonashaag
